{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.postgres.usernameKey }}: {{ .Values.secret.postgresUsername | b64enc }}
  {{ .Values.secrets.postgres.passwordKey }}: {{ .Values.secret.postgresPassword | b64enc }}
  {{ .Values.secrets.encryptionKey }}: {{ .Values.secret.encryptionKey | b64enc }}
{{- end }}
