apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
