apiVersion: v2
name: n8n
description: A Helm chart for deploying n8n automation platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - n8n
  - automation
  - workflow
home: https://n8n.io
sources:
  - https://github.com/n8n-io/n8n
maintainers:
  - name: CalebSargeant
